from snakemake.utils import validate


configfile: "config/config.yaml"


container: "docker://condaforge/mambaforge:4.10.3-6"


include: "rules/common.smk"
include: "rules/input_resources.smk"
include: "rules/lift_resources.smk"
include: "rules/cellranger_resources.smk"
include: "rules/lift.smk"
include: "rules/cellranger.smk"
include: "rules/qc_reads.smk"


rule report:
    input:
        "results/multiqc/multiqc.html",
        **agg_cr_html(),
