$schema: "http://json-schema.org/draft-07/schema#"

description: Config File Schema

properties:
  samples:
    description: Samplesheet location
    type: string

  lift:
    description: PolyA_DB Coordinates
    type: string

  get_cellranger:
    description: Step Parametres
    type: object
    properties:
      url: { type: string }
    required: [ url ]
    additionalProperties: false

  get_gtf:
    description: Step Parametres
    type: object
    properties:
      url: { type: string }
    required: [ url ]
    additionalProperties: false

  get_fa:
    description: Step Parametres
    type: object
    properties:
      url: { type: string }
    required: [ url ]
    additionalProperties: false

  get_9_to_10:
    description: Step Parametres
    type: object
    properties:
      url: { type: string }
    required: [ url ]
    additionalProperties: false

  get_10_to_39:
    description: Step Parametres
    type: object
    properties:
      url: { type: string }
    required: [ url ]
    additionalProperties: false

  counts:
    description: Step Parametres
    type: object
    properties:
      introns: { type: boolean }
      n_cells: { type: integer }
      mem: { type: integer }
    required: [ introns, n_cells, mem ]
    additionalProperties: false

additionalProperties: false
required:
  - samples
  - get_cellranger
  - get_gtf
  - get_fa
  - get_9_to_10
  - get_10_to_39
  - counts
